version: 2

updates:

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 4 * * *"
    open-pull-requests-limit: 1
    labels: [ "dependencies", "maven" ]
    commit-message:
      prefix: "deps"
      include: "scope"
    assignees:
      - "JarandDev"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 4 * * *"
    open-pull-requests-limit: 1
    labels: [ "dependencies", "github-actions" ]
    commit-message:
      prefix: "ci"
      include: "scope"
    assignees:
      - "JarandDev"
    groups:
      all-actions:
        patterns:
          - "*"
